server:
  port: 9081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./database/mydb;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:./database/mydb;DB_CLOSE_ON_EXIT=FALSE;IF_EXISTS=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always